### ISSUE TITLE
Why there is not getRows() ?

### ISSUE THREAD

**Issue by iit2011081** [graphaware/neo4j-php-client#108]
I am migrating my client from neoxygen/neo4-client to this client. But to my surprise the syntax is different and there is no getRows() in this client. Is there any alternative of getRows() in this client ?

**Comment by ikwattro** [comment]
There isn't, the Result API has been refactored completely to match neo4j official drivers. There are breaking changes and users of neoxygen client have been warned since more than a year.

The README contains as much informations for using the Result objects as well as migrating from v3. `getRows` is now a Record object that you receive on each iteration of `Result::records()`
