### ISSUE TITLE
labels()

### ISSUE THREAD

**Issue by calpirro** [graphaware/neo4j-php-client#20]
Hi, in documentation you say:

`labels() : returns an array of labels (string)`

I think it doesn't exist, Is it the function **keys()** ?

Thanks

**Comment by ikwattro** [comment]
No it exist : https://github.com/graphaware/neo4j-php-client/blob/master/src/Formatter/Type/Node.php#L51

It is only available for node objects, like stated in the readme https://github.com/graphaware/neo4j-php-client#node

What made you think it wasn't existing ?

**Comment by calpirro** [comment]
Sure it's my fault... I'm trying to migrate from v3 to v4 and everything it's different... :-(

In this code:

```
$r = $this -> db -> run($q) -> getRecords();
foreach ($r as $element){
   foreach ($element -> labels() as $ident)
```

I got this error:

`Fatal error: Call to undefined method GraphAware\Neo4j\Client\Formatter\RecordView::labels()`

BTW the keys() function is not listed in the README.

**Comment by ikwattro** [comment]
Good to hear.

Yes it is different, but for the good I hope. The API is unified with the neo4j official drivers technology compliance kit. 

In order to guide you : 

When you do : 

```php
$r = $this->db->run($q)->getRecords()
```

It will return you a collection of `Record` objects. You can view a record as a row in the neo4j browser : 

![screen shot 2016-04-27 at 15 10 35](https://cloud.githubusercontent.com/assets/1222009/14857102/e25b8fe2-0c92-11e6-8f3e-e3b96fa80ac7.png)

So you need to access the record values with the `value` method where the `key` is the column name : 

```php
$r = $this -> db -> run($q) -> getRecords();
foreach ($r as $record) {
    foreach ($record->get('key') as $node) { // here replace "key" with your actual identifier
       foreach ($node->labels() as $ident) {
            echo $ident;
     }
   }
}
```

Thanks for the `keys` method heads up for the readme
