### ISSUE TITLE
Self or create relation urls

### ISSUE THREAD

**Issue by tomswinkels** [graphaware/neo4j-php-client#57]
When i create some new note with curl, than i get an ouput with a self and create relation url. 

Is there any option how to get the urls with the neo4j-php-client?

Thanks,

Tom

**Comment by ikwattro** [comment]
@tomswinkels 

Simple answer: no

Long answer: will be to the point without intention to offense, but just honest view of me.

the client is Cypher-Endpoint centrix, if you create a node with the very very old REST API, you are years behind what is actually happening in neo4j.

Secondly the client is driver agnostic and offers the same api if you use http or the new binary protocol of neo4j since Neo4j 3.0.

Please upgrade your neo4j development strategy !

**Comment by tomswinkels** [comment]
@ikwattro 

Thanks for you're answer :)
