### ISSUE TITLE
Empty array as parameter

### ISSUE THREAD

**Issue by theUm** [graphaware/neo4j-php-client#99]
Empty array passing to parameter in SET queries leads to `Property values can only be of primitive types or arrays thereof`. Non-empty arrays works okay. In neo4j web browser empy arrays with such syntax are also okay.
Here's code:
`        $res = $em->getDatabaseDriver()->run(
            'MATCH (n) WHERE id(n) = {id} SET n += {props}',
            [
                'id' => '%someNumericId%',
                'props' => ['somevalue'=>true, 'someArray' => []]
            ]
        );
`

**Comment by ikwattro** [comment]
Hi @theUm , can you confirm the behavior is same with http and bolt ?

**Comment by theUm** [comment]
`"name": "graphaware/neo4j-bolt", "version": "1.9.1",`
` "name": "graphaware/neo4j-php-client",  "version": "4.8.0"`
Initial test was with bolt. Yep, same on http:
`Neo4j Exception with code "Neo.ClientError.Statement.TypeError" and message "Property values can only be of primitive types or arrays thereo`.
I do not tesed that with curl, maybe its completely normal behaviour, and neo4j web browser has workaround?

**Comment by ikwattro** [comment]
Unfortunately this is more complex than that, mainly because of PHP's missing type system.

When a passed array is empty, it is very hard to determine if it should be passed as an empty List or an empty Map for Cypher, there are some tips and tricks but they don't work in all cases, like this one.

I'm afraid the only way to make it 100% possible is to introduce a `Collections::emptyMap()` or `Collections::emptyList()` methods that you would have to use.

**Comment by ikwattro** [comment]
This has been fixed in Bolt now, check https://github.com/graphaware/neo4j-bolt-php/pull/23 Same fix is coming for http

**Comment by iit2011081** [comment]
Is it fixed for http ?
